config/routes.rb
Rails.application.routes.draw do

  get   '/login'  => "session#new",     as: "new_login"
  post  '/login'  => "session#create",  as: 'login'
  get   '/logout' => "session#destroy", as: 'logout'

  get   '/register' => "register#new",    as: 'registration'
  post  '/register' => "register#create", as: 'register'

  resource :shopping_cart, only: [:show], controller: 'shopping_cart' do
    get :pre_checkout
    put :checkout
    put '/:product_id', action: :update, as: 'update'
    delete '/:product_id', action: :destroy, as: 'destroy'
  end

  get '/thank_you' => "pages#thank_you", as: 'thank_you'

  get   '/about'  => "pages#about",  as: 'about'

  get  '/contact', to: 'contact#new'
  post '/contact', to: 'contact#create'

  resource :profile, only: [:show, :update] do
    get :welcome, on: :collection
    get :previous_orders
  end

  namespace :admin do
    resources :people, only: [:index, :edit, :update]
    resources :products, only: [:index, :edit, :update, :new, :create]
    resources :orders, only: [:index, :edit, :update] do
      resources :payments, only: [:destroy], controller: 'order_payments'
    end
    root "dashboard#show"
  end

  resources :products, only: [:show]

  root "pages#landpage"
end

app/views/admin/_copyright.html.erb
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
<%= t('.copyright')%> &copy; <%= Date.today.year %>
<%= t('.all_rights_reserved')%> | <%= t('.this_is_made')%> <i class="fa fa-heart" aria-hidden="true"></i> <%= t('.by')%> <a href="https://colorlib.com" target="_blank">Colorlib.com</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->

app/views/admin/_sidebar.html.erb
<div class="custom-menu">
  <button type="button" id="sidebarCollapse" class="btn btn-primary">
    <i class="fa fa-bars"></i>
    <span class="sr-only">Toggle Menu</span>
  </button>
</div>
<div class="p-4 pt-5 d-flex flex-column flex-grow-1">
  <h1><%= link_to "Admin", admin_root_path, class: "logo" %></h1>
  <ul class="list-unstyled components mb-5">
    <li>
      <%= link_to admin_root_path do %>
        <i class="fas fa-fw fa-chart-line mr-3"></i>
        <%= t('.dashboard')%>
      <% end %>
    </li>
    <li>
      <%= link_to admin_people_path do %>
        <i class="fas fa-fw fa-users mr-3"></i>
        <%= Person.model_name.human(count:2) %>
      <% end %>
    </li>
    <li>
      <%= link_to admin_orders_path do %>
        <i class="fas fa-fw fa-truck mr-3"></i>
        <%= Order.model_name.human(count:2) %>
      <% end %>
    </li>
    <li>
      <%= link_to admin_products_path do %>
        <i class="fas fa-fw fa-boxes mr-3"></i>
        <%= Product.model_name.human(count:2) %>
      <% end %>
    </li>
    <li>
      <%= link_to root_path do %>
        <i class="fas fa-fw fa-store mr-3"></i>
        <%= t('.go_to_store')%>
      <% end %>
    </li>
  </ul>

  <div class="footer mt-auto">
    <p>
      <%= render partial: 'admin/copyright'%>
    </p>
  </div>
</div>