config/routes.rb
Rails.application.routes.draw do

  get   '/login'  => "session#new",     as: "new_login"
  post  '/login'  => "session#create",  as: 'login'
  get   '/logout' => "session#destroy", as: 'logout'

  get   '/register' => "register#new",    as: 'registration'
  post  '/register' => "register#create", as: 'register'

  resource :shopping_cart, only: [:show], controller: 'shopping_cart' do
    get :pre_checkout
    put :checkout
    put '/:product_id', action: :update, as: 'update'
    delete '/:product_id', action: :destroy, as: 'destroy'
  end

  get '/thank_you' => "pages#thank_you", as: 'thank_you'

  get   '/about'  => "pages#about",  as: 'about'

  get  '/contact', to: 'contact#new'
  post '/contact', to: 'contact#create'

  resource :profile, only: [:show, :update] do
    get :welcome, on: :collection
    get :previous_orders
  end

  namespace :admin do
    resources :people, only: [:index, :edit, :update]
    resources :products, only: [:index, :edit, :update, :new, :create]
    resources :orders, only: [:index, :edit, :update] do
      resources :payments, only: [:destroy], controller: 'order_payments'
    end
    root "dashboard#show"
  end

  resources :products, only: [:show]

  root "pages#landpage"
end

app/models/order.rb
class Order
    include Mongoid::Document
    include Mongoid::Timestamps
    include Mongoid::Enum

    belongs_to :user, inverse_of: :orders
    has_many :order_items, dependent: :destroy
    has_many :payments, inverse_of: :order, dependent: :destroy

    enum :status, [:pending, :waiting_payment, :accepted, :dispatched, :closed, :denied, :waiting_refund, :refunded]

    field :delivery_country, type: String
    field :delivery_administrative, type: String
    field :delivery_city, type: String
    field :delivery_address, type: String
    field :delivery_fee, type: Float, default: 0
    field :delivery_eta_date, type: DateTime
    field :total, type: Float, default: 0
    field :dispatch_at, type: DateTime

    def can_checkout?
        order_items.exists? && pending?
    end

    def calculate_total
        order_items.inject(0){|sum,e| sum += e.quantity * e.product.price}
    end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController
  before_action :order_required!, only: [:edit, :update]

  def index
    @orders = Order.order(created_at: :desc).all
  end

  def edit
  end

  def update
    if order.update_attributes(update_params)
      order.update_attribute(:dispatch_at, Time.now) if order.status_previously_changed? && order.dispatched?
      redirect_to admin_orders_path, notice: t('notices.saved_with_success')
    else
      flash[:alert] = order.errors.full_message
      render 'edit'
    end
  end

  private

  def order
    @order ||= Order.where(id: params[:id]).first
  end

  def update_params
    extract_params :order, permit:[:status]
  end

  def order_required!
    redirect_to(admin_orders_path, alert: t('error.not_found')) unless order.present?
  end

end

app/views/admin/orders/_form.html.erb
<%= form_for [:admin, @order] do |f| %>

  <div class="form-group">
    <%= f.label :status %>
    <%= f.select :status, Order::STATUS.map{|e| [Order.human_attribute_name('status/%s' % e), e]}, {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit t('shared.save'),  class: 'btn btn-primary' %>
    <%= link_to t('shared.back'), admin_orders_path, class: 'btn btn-link'%>
  </div>

<% end %>

app/views/admin/orders/edit.html.erb
<h1><%= Order.model_name.human(count: 1) %> <%= @order.id %> </h1>

<h3><small><i class="fas fa-fw fa-boxes"></i></small> <%= Product.model_name.human(count: 2) %></h3>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th scope="col"><%= OrderItem.human_attribute_name(:product_title) %></th>
        <th scope="col"><%= OrderItem.human_attribute_name(:quantity) %></th>
        <th  class="text-right" scope="col"><%= OrderItem.human_attribute_name(:total) %></th>
      </tr>
    </thead>
    <tbody>
      <% @order.order_items.each do |item| %>
        <tr>
          <th scope="row"><%= item.product_title%></th>
          <td ><%= item.quantity %></td>
          <td class="text-right"><%= number_to_currency(item.total, unit: "€") %></td>
        </tr>
      <% end %>
        <tr>
          <th scope="row"></th>
          <td></td>
          <td class="text-right"><strong><%= number_to_currency(@order.total, unit: "€") %></strong></td>
        </tr>
    </tbody>
  </table>
</div>

<h3><small><i class="fas fa-fw fa-truck"></i></small> <%= t('.ship_to') %></h3>
<div class="mb-5">
  <p class="text-dark mb-1"><%= link_to @order.user.name, edit_admin_person_path(@order.user), class:'font-weight-bold' %></p>
  <p class="text-dark mb-1"><%= @order.delivery_country %></p>
  <p class="text-dark mb-1"><%= @order.delivery_administrative %></p>
  <p class="text-dark mb-1"><%= @order.delivery_city %></p>
  <p class="text-dark mb-1"><%= @order.delivery_address %></p>
</div>


<h3><small><i class="fas fa-fw fa-credit-card"></i></small> <%= Payment.model_name.human(count: 2) %></h3>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th scope="col"><%= Payment.human_attribute_name(:created_at) %></th>
        <th scope="col"><%= Payment.human_attribute_name(:status) %></th>
        <th  class="text-right" scope="col"><%= Payment.human_attribute_name(:total) %></th>
      </tr>
    </thead>
    <tbody>
      <% @order.payments.each do |item| %>
        <tr class="<%= 'text-danger' if item.failed? %>">
          <td><%= l(item.created_at, format: :long) %></td>
          <td>
            <small><%= content_tag(:i, nil, class: 'fas fa-fw fa-exclamation-triangle cursor-help', title: item.reason) if item.reason.present?%></small>
            <%= Payment.human_attribute_name('status/%s' % item.status) %>
            <%= link_to(t('shared.refund'), admin_order_payment_path(order_id: item.order_id, id: item.id), method: :delete, confirm: t('shared.are_you_sure')) if item.complete? %>
          </td>
          <td class="text-right"><%= number_to_currency(item.total, unit: "€") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>




<%= render 'form' %>

app/views/admin/orders/index.html.erb
<h1><%= Order.model_name.human(count: 2) %></h1>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th scope="col"><%= Order.human_attribute_name(:user) %></th>
        <th scope="col"><%= Order.human_attribute_name(:item_quantity) %></th>
        <th scope="col"><%= Order.human_attribute_name(:status) %></th>
        <th scope="col"><%= Order.human_attribute_name(:total) %></th>
        <th scope="col"><%= Order.human_attribute_name(:dispatched_at) %></th>
      </tr>
    </thead>
    <tbody>
    <% @orders.each do |order| %>
    <tr>
      <td><%= order.user.is_a?(Guest) ? "Guest" : order.user.name %></td>
      <td><%= order.order_items.sum(:quantity) %></td>
      <td><%= link_to Order.human_attribute_name('status/%s' % order.status.to_s), edit_admin_order_path(order) %></td>
      <td><%= number_to_currency(order.total, unit: "€") %></td>
      <td><%= order.dispatch_at %></td>
    </tr>
    <% end %>
  </tbody>
  </table>
</div>