config/routes.rb
Rails.application.routes.draw do

  get   '/login'  => "session#new",     as: "new_login"
  post  '/login'  => "session#create",  as: 'login'
  get   '/logout' => "session#destroy", as: 'logout'

  get   '/register' => "register#new",    as: 'registration'
  post  '/register' => "register#create", as: 'register'

  resource :shopping_cart, only: [:show], controller: 'shopping_cart' do
    get :pre_checkout
    put :checkout
    put '/:product_id', action: :update, as: 'update'
    delete '/:product_id', action: :destroy, as: 'destroy'
  end

  get '/thank_you' => "pages#thank_you", as: 'thank_you'

  get   '/about'  => "pages#about",  as: 'about'

  get  '/contact', to: 'contact#new'
  post '/contact', to: 'contact#create'

  resource :profile, only: [:show, :update] do
    get :welcome, on: :collection
    get :previous_orders
  end

  namespace :admin do
    resources :people, only: [:index, :edit, :update]
    resources :products, only: [:index, :edit, :update, :new, :create]
    resources :orders, only: [:index, :edit, :update] do
      resources :payments, only: [:destroy], controller: 'order_payments'
    end
    root "dashboard#show"
  end

  resources :products, only: [:show]

  root "pages#landpage"
end

app/views/shared/_alerts.html.erb
<% if flash[:notice].present? %>
  <% [flash[:notice]].flatten.each do |msg| %>
    <div class="alert alert-success" role="alert">
      <%= msg %>
    </div>
  <% end %>
<% end %>

<% if flash[:alert].present? %>
  <% [flash[:alert]].flatten.each do |err| %>
    <div class="alert alert-danger" role="alert">
      <%= err %>
    </div>
  <% end %>
<% end %>

app/views/shared/_cart_widget.html.erb
<%= link_to shopping_cart_path do %>
<div id="cart-widget" class="<%= 'active' if shopping_cart_total_quantity > 0 %>">
  <small class="d-block text-center"><%= t('shared.shopping_cart') %></small>
  <div class="d-flex align-items-center justify-content-space-between">
    <span class="amount"><%= shopping_cart_total_quantity %></span>
    <span><i class="fas fa-fw fa-shopping-basket"></i></span>
    <span class="total"><%= number_to_currency(shopping_cart_total) %></span>
  </div>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav id="navbar" class="navbar navbar-dark bg-dark sticky-top text-light navbar-fixed">
  <%= link_to "NCI GameStore", root_path, class: "navbar-brand" %>

  <div class="navbar-toolbox">
    <%= navbar_link("fas fa-question", t('navbar.about'), about_path) %>
    <%= navbar_link("fas fa-envelope", t('navbar.contact'), contact_path) %>

    <%#= navbar_link("fas fa-shopping-basket", t('shared.see_shopping_cart'), shopping_cart_path) if current_user.try(:has_shopping_cart?) %>

    <% if current_user.is_a?(Guest) %>
      <%= navbar_link("fas fa-user-secret", t('shared.abandon'), logout_path) %>
      <%= navbar_link("fas fa-key", t('shared.login'), new_login_path) %>
    <% elsif current_user.is_a?(Person) %>
      <%= navbar_link("fas fa-user", t('navbar.profile'), profile_path) %>
      <%= navbar_link("fas fa-lock", t('navbar.admin'), admin_root_path) if current_user.admin? %>
      <%= navbar_link("fas fa-power-off", t('shared.logout'), logout_path) %>
    <% else %>
      <%= navbar_link("fas fa-key", t('shared.login'), new_login_path) %>
    <% end %>
  </div>
</nav>

app/views/shared/_product_cart_button.html.erb
<div class="product-cart-button-<%= product.id %>">
  <% if in_shopping_cart?(product) %>
    <%= link_to update_shopping_cart_path(product, 'product[quantity]' => 1, 'product[increment]' => true), method: :put, remote: true, class: 'btn btn-info mt-3' do%>
    <i class="fas fa-shopping-cart"></i> <%= t('shared.quantity_cart', number: get_product_amount(product)) %>
    <% end %>
  <% elsif product.in_stock? %>
    <%= link_to update_shopping_cart_path(product, 'product[quantity]' => 1, 'product[increment]' => true), method: :put, remote: true, class: 'btn btn-danger mt-3' do%>
    <i class="fas fa-shopping-cart"></i> <%= t('shared.add_to_cart')%>
    <% end %>
  <% end %>
</div>