config/routes.rb
Rails.application.routes.draw do

  get   '/login'  => "session#new",     as: "new_login"
  post  '/login'  => "session#create",  as: 'login'
  get   '/logout' => "session#destroy", as: 'logout'

  get   '/register' => "register#new",    as: 'registration'
  post  '/register' => "register#create", as: 'register'

  resource :shopping_cart, only: [:show], controller: 'shopping_cart' do
    get :pre_checkout
    put :checkout
    put '/:product_id', action: :update, as: 'update'
    delete '/:product_id', action: :destroy, as: 'destroy'
  end

  get '/thank_you' => "pages#thank_you", as: 'thank_you'

  get   '/about'  => "pages#about",  as: 'about'

  get  '/contact', to: 'contact#new'
  post '/contact', to: 'contact#create'

  resource :profile, only: [:show, :update] do
    get :welcome, on: :collection
    get :previous_orders
  end

  namespace :admin do
    resources :people, only: [:index, :edit, :update]
    resources :products, only: [:index, :edit, :update, :new, :create]
    resources :orders, only: [:index, :edit, :update] do
      resources :payments, only: [:destroy], controller: 'order_payments'
    end
    root "dashboard#show"
  end

  resources :products, only: [:show]

  root "pages#landpage"
end

app/controllers/shopping_cart_controller.rb
class ShoppingCartController < ApplicationController

  before_action :create_guest, only: :update
  before_action :require_any_user
  before_action :ensure_cart_can_be_checked_out, only: [:pre_checkout, :checkout]

  def show
    @cart = service.cart
  end

  def update
    process = service.add_item(params[:product_id], update_params[:quantity], increment: update_params[:increment])
    if process.success?
      @deleted = process.item_removed?
      @cart = service.cart
      @total = @cart.calculate_total
      @quantity = @cart.order_items.sum(:quantity)
      @order_item = process.get(:order_item)
      respond_to do |format|
        format.js
        format.html {
          redirect_to shopping_cart_path, notice: t('notices.item_updated', title: process.get(:product).try(:title))
        }
      end

    else
      redirect_to shopping_cart_path, alert: t('errors.oops')
    end
  end

  def destroy
    process = service.remove_item(params[:product_id])
    redirect_to shopping_cart_path, notice: t('errors.item_removed')
  end

  def pre_checkout
    @cart = service.cart
  end

  def checkout
    process = service.checkout(checkout_params)
    if process.success?
      redirect_to thank_you_path, notice: t('notices.checkout_complete')
    else
      redirect_to({action: :pre_checkout}, alert: process.errors)
    end
  end

  private

  def service
    @service ||= ShoppingCartService.new(current_user)
  end

  def update_params
    extract_params :product, permit: [:quantity, :increment]
  end

  def checkout_params
    extract_params :order, permit: [
      :delivery_country,
      :delivery_administrative,
      :delivery_city,
      :delivery_address,
      :stripe_token
    ]
  end

  def create_guest
    return if current_user.present?
    swap_cookie(Guest.create)
  end

  def ensure_cart_can_be_checked_out
    redirect_to(shopping_cart_path, alert: t('errors.cannot_checkout')) unless service.cart.can_checkout?
  end

end

app/helpers/shopping_cart_helper.rb
module ShoppingCartHelper
end

app/views/shopping_cart/_item.html.erb
<div class="col-12" id="shopping-cart-item-<%= item.id %>">
  <div class="card mb-3">


    <div class="card-body d-flex flex-column">
      <div class="row">

        <div class="col-8">
          <%= image_tag item.product.image_url.presence || image_path('placeholder.png'), alt: item.product.title %>
          <%= link_to item.product.title, product_path(item.product)%>
        </div>

        <div class="col-2">
          <%= link_to update_shopping_cart_path(item.product, 'product[quantity]' => item.quantity-1), method: :put, remote: true do %>
            <i class="fas fa-minus-square"></i>
          <% end %>
          <%= content_tag :span, item.quantity, class: 'mx-2' %>
          <%= link_to update_shopping_cart_path(item.product, 'product[quantity]' => item.quantity+1), method: :put, remote: true do %>
            <i class="fas fa-plus-square"></i>
          <% end %>
        </div>

        <div class="col-2 text-right">
          <%= number_to_currency (item.product.price*item.quantity) %>
          <%= link_to destroy_shopping_cart_path(item.product), class: 'ml-2', method: :delete, data: {confirm: t('shared.are_you_sure')} do %>
            <i class="fas fa-times-circle"></i>
          <% end %>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/shopping_cart/pre_checkout.html.erb
<div class="container">

  <%= render partial: 'shared/alerts'%>


  <div class="w-50 mx-auto my-5">
    <div id="card-element"></div>
    <div id="card-errors"></div>
  </div>


  <div class="col-12">
    <%= form_with(model: @cart, url: checkout_shopping_cart_path, id: 'payment-form', method: :put) do |f|%>
    <p><%= t('.amount_due')%> <%= number_to_currency @cart.calculate_total %></p>

    <div class="form-group">
      <%= f.label :delivery_country %>
      <%= f.text_field :delivery_country, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :delivery_administrative %>
      <%= f.text_field :delivery_administrative, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :delivery_city %>
      <%= f.text_field :delivery_city, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :delivery_address %>
      <%= f.text_field :delivery_address, class: 'form-control' %>
    </div>

    <div class="text-center">
      <%= f.submit t('shared.checkout'), id: 'submit-button', class: 'btn btn-success btn-lg', data: {disable_with: t('shared.sending')} %>
    </div>
    <% end %>
  </div>

</div>
<script>
  var stripe = Stripe("<%= Rails.application.credentials.stripe[:public_key] %>");
  var elements = stripe.elements();

  var style = {
    base: {
      color: '#32325d',
      fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
      fontSmoothing: 'antialiased',
      fontSize: '16px',
      '::placeholder': {
        color: '#aab7c4'
      }
    },
    invalid: {
      color: '#fa755a',
      iconColor: '#fa755a'
    }
  };

  var card = elements.create('card', { style: style, hidePostalCode: true });
  var form = document.getElementById('payment-form');
  var submit = document.getElementById('submit-button');
  card.mount('#card-element');

  card.addEventListener('change', function (event) {
    if(submit.disabled){
      $.rails.enableElement(submit);
    }

    var displayError = document.getElementById('card-errors');
    if (event.error) {
      displayError.textContent = event.error.message;
    } else {
      displayError.textContent = '';
    }
  });

  form.addEventListener('ajax:before', function (event) {
    event.preventDefault();

    stripe.createToken(card).then(function (result) {
      if (result.error) {
        // Inform the user if there was an error.
        var errorElement = document.getElementById('card-errors');
        errorElement.textContent = result.error.message;
        enable();
      } else {
        // Send the token to your server.
        stripeTokenHandler(result.token);
      }
    });
  });

  function enable(){
    setTimeout(() => {
      $.rails.enableElement(submit);
    }, 1000);
  }

  // Submit the form with the token ID.
  function stripeTokenHandler(token) {
    // Insert the token ID into the form so it gets submitted to the server
    var form = document.getElementById('payment-form');
    var hiddenInput = document.createElement('input');
    hiddenInput.setAttribute('type', 'hidden');
    hiddenInput.setAttribute('name', 'order[stripe_token]');
    hiddenInput.setAttribute('value', token.id);
    form.appendChild(hiddenInput);

    // Submit the form
    form.submit();
  }



</script>

app/views/shopping_cart/show.html.erb
<div class="container-fluid">
  <%= render partial: 'shared/alerts'%>
  <h2><%= t('.title') %></h2>

  <div class="shopping_cart_items row">
    <%= render partial:'item', collection: @cart.order_items %>

    <div class="col-12 d-flex justify-content-end" id="shopping-cart-total">
      <%= number_to_currency @cart.calculate_total %>
    </div>
  </div>


  <div class="text-center">

    <% if current_user.is_a?(Person)%>
    <%= link_to t('shared.checkout'), pre_checkout_shopping_cart_path, class: 'btn btn-success btn-lg' if @cart.can_checkout? %>
    <% else %>
    <%= link_to t('.must_login'), login_path(redirect_to: shopping_cart_url), class: 'btn btn-success btn-lg' %>
    <% end %>
  </div>

</div>